### ISSUE TITLE
Refactoring removes comments from method

### ISSUE THREAD

**Issue by prateekbaheti** [getgauge/gauge-java#16]
Eg.: for step
```* A step```
````java
    @Step("A step")
    public void contextStep() {
   // some comment
    }
````

On Refactoring
```gauge --refactor "A step"  "Changed step"```
The method changes:
````java
    @Step("Changed step")
    public void contextStep() {
    }
````

The comment is removed.

**Comment by prateekbaheti** [comment]
Caused due to a [bug](https://github.com/rpau/javalang/issues/11) in the java parsing library used.

**Comment by Thunderforge** [comment]
It looks like the bug in the library was fixed several months ago. Will this be fixed in Gauge?

**Comment by mahendrakariya** [comment]
We have already updated the library. But this bug is caused by something else. We will be fixing it soon.

**Comment by mahendrakariya** [comment]
Apparently, this is still an issue with Java Parser library.
https://github.com/javaparser/javaparser/issues/192

**Comment by ftomassetti** [comment]
From JavaParser: I think we fixed this in master but now yet released a new version

**Comment by mahendrakariya** [comment]
Thanks @ftomassetti for the quick response. By when can we expect you to release this fix?

**Comment by ftomassetti** [comment]
we do not have immediate plans for a new release and we currently have a bunch of PRs open so I am not sure but I guess not in the next few weeks

**Comment by mahendrakariya** [comment]
I tried out v2.2.2 of java parser library which was released today. The issue is still not resolved.

**Comment by Thunderforge** [comment]
Version 2.3.0 was just released. It would be good to try it with that, especially since the bug report seems to indicate that it was properly fixed after the release of v2.2.2.

**Comment by mahendrakariya** [comment]
Tried with v2.3.0. I don't think the issue has been resolved yet.

**Comment by mahendrakariya** [comment]
The fix is released in gauge-java 0.3.3.
