### ISSUE TITLE
JVM based language like Kotlin does not work on 0.7.4

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/gauge-java#390]
### Expected behavior
Step implementations written in kotlin to work fine in maven project.

### Actual behavior
Throws validation error as steps are not recognised

### Steps to reproduce
Convert java implementation files to kotlin in https://github.com/getgauge-examples/java-maven-selenium and run spec.

### Gauge version
```
Gauge version: 1.0.7

Plugins
-------

html-report (4.0.9)
java (0.7.4)
screenshot (0.0.1)
```

#### Dev note
cc: @BugDiver 
When we implemented the LSP features, we break the runner life cycle in two parts
static scanning for/till validation and refactoring or some other lsp features
Execution phase where it scan using reflection
But it was scanning using reflections as well while doing static scanning, so the kotlin implementation might got scanned and execution worked

But later we fix it ( after grpc) and stopped reflecting unless we reached execution phase

**Comment by coding-lama** [comment]
Hi team, any updates or estimates when this issue will be resolved? We are stuck with the old version of gauge and its causing issues in reports...
Thanks.

**Comment by zabil** [comment]
You can check the priority(order under "Ready for Development) and progress of this issue at 
https://github.com/orgs/getgauge/projects/6

**Comment by coding-lama** [comment]
Hi team, I see that new gauge-java 0.75 is out, however it does not look like this issue was solved in that version. Can anybody from the devs confirm please?
Thanks.

**Comment by sriv** [comment]
Yes, this issue is still to be resolved. You can see the changelog for `0.7.5` here - https://github.com/getgauge/gauge-java/releases/tag/v0.7.5

**Comment by coding-lama** [comment]
Hey guys, congrats on solving this issue, when will this fix be available for us to use? 
Thanks in advance.

**Comment by sriv** [comment]
gauge-java 0.7.7 is released. Please check.
